# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GNI18N-iOS-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GNI18N-iOS-Demo
  pod 'WKWebViewJavascriptBridge', '~> 1.2.0'
  pod 'SwiftyUserDefaults', '~> 5.0'

end
